SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

DROP TABLE IF EXISTS `permissions`;
CREATE TABLE `permissions` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `guard_name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `display_name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `permission_group` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` varchar(191) COLLATE utf8mb4_unicode_ci  NULL,
  `routes` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
   PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=73 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `permissions`
--

INSERT INTO `permissions` (`id`, `name`, `guard_name`, `display_name`, `permission_group`,`description` ,`routes`, `created_at`, `updated_at`) VALUES
(2, 'categories', 'web', 'مشاهدة الاقسام', 'الاقسام', NULL,'categories.index', NULL, NULL),
(3, 'add_category', 'web', 'اضافة قسم', 'الاقسام', NULL,'categories.create,categories.store', NULL, NULL),
(4, 'update_category', 'web', 'تعديل الاقسام', 'الاقسام', NULL,'categories.update,categories.edit', NULL, NULL),
(5, 'delete_category', 'web', 'حذف الاقسام', 'الاقسام', NULL,'categories.destroy', NULL, NULL),
(6, 'activate_categories', 'web', 'تفعيل والغاء تفعيل الاقسام', 'الاقسام', NULL,'categories_activation', NULL, NULL),
(7, 'job-types', 'web', 'مشاهدة انواع الوظائف', 'انواع الوظائف',NULL, 'job-types.index', NULL, NULL),
(8, 'add_job-types', 'web', 'اضافة نوع وظييفة', 'انواع الوظائف',NULL, 'job-types.create,job-types.store', NULL, NULL),
(9, 'update_job-types', 'web', 'تعديل انواع الوظائف', 'انواع الوظائف',NULL, 'job-types.update,job-types.edit', NULL, NULL),
(10, 'delete_job-types', 'web', 'حذف انواع الوظائف', 'انواع الوظائف', NULL,'job-types.destroy', NULL, NULL),
(11, 'tag', 'web', 'مشاهدة الكلمات الدلالية', 'الكلمات الدلالية',NULL, 'tag.index', NULL, NULL),
(12, 'add_tag', 'web', 'اضافة كلمة دلالية', 'الكلمات الدلالية', NULL,'tag.create,tag.store', NULL, NULL),
(13, 'update_tag', 'web', 'تعديل الكلمات الدلالية', 'الكلمات الدلالية',NULL, 'tag.update,tag.edit', NULL, NULL),
(14, 'delete_tag', 'web', 'حذف الكلمات الدلالية', 'الكلمات الدلالية',NULL, 'tag.destroy', NULL, NULL),
(15, 'products', 'web', 'مشاهدة المنتجات', 'المنتجات',NULL, 'products.index', NULL, NULL),
(16, 'add_products', 'web', 'اضافة منتج', 'المنتجات', NULL,'products.create,products.store', NULL, NULL),
(17, 'update_products', 'web', 'تعديل المنتجات', 'المنتجات',NULL, 'products.update,products.edit', NULL, NULL),
(18, 'delete_products', 'web', 'حذف المنتجات', 'المنتجات',NULL, 'products.destroy', NULL, NULL),
(19, 'activate_products', 'web', 'تفعيل والغاء تفعيل المنتجات', 'المنتجات', NULL,'products_activation', NULL, NULL),
(20, 'posts', 'web', 'مشاهدة المقالات', 'المقالات',NULL, 'posts.index', NULL, NULL),
(21, 'add_posts', 'web', 'اضافة مقال', 'المقالات', NULL,'posts.create,posts.store', NULL, NULL),
(22, 'update_posts', 'web', 'تعديل المقالات', 'المقالات',NULL, 'posts.update,posts.edit', NULL, NULL),
(23, 'delete_posts', 'web', 'حذف المقالات', 'المقالات',NULL, 'posts.destroy', NULL, NULL),
(24, 'activate_posts', 'web', 'تفعيل والغاء تفعيل المقالات', 'المقالات', NULL,'posts_activation', NULL, NULL),
(25, 'sliders', 'web', 'مشاهدة الشرائح', 'الشرائح',NULL, 'sliders.index', NULL, NULL),
(26, 'add_sliders', 'web', 'اضافة شريحة', 'الشرائح',NULL, 'sliders.create,sliders.store', NULL, NULL),
(27, 'update_sliders', 'web', 'تعديل الشرائح', 'الشرائح',NULL, 'sliders.update,sliders.edit', NULL, NULL),
(28, 'delete_sliders', 'web', 'حذف الشرائح', 'الشرائح',NULL, 'sliders.destroy', NULL, NULL),
(29, 'activate_sliders', 'web', 'تفعيل والغاء تفعيل الشرائح', 'الشرائح',NULL, 'sliders_activation', NULL, NULL),
(30, 'services', 'web', 'مشاهدة الخدمات', 'الخدمات',NULL, 'services.index', NULL, NULL),
(31, 'add_services', 'web', 'اضافة خدمة', 'الخدمات',NULL, 'services.create,services.store', NULL, NULL),
(32, 'update_services', 'web', 'تعديل الخدمات', 'الخدمات',NULL, 'services.update,services.edit', NULL, NULL),
(33, 'delete_services', 'web', 'حذف الخدمات', 'الخدمات',NULL, 'services.destroy', NULL, NULL),
(34, 'activate_services', 'web', 'تفعيل والغاء تفعيل الخدمات', 'الخدمات',NULL, 'services_activation', NULL, NULL),
(35, 'services.feature', 'web', 'مشاهدة مميزات الخدمة', 'مميزات الخدمة',NULL, 'services.feature.index', NULL, NULL),
(36, 'add_services.feature', 'web', 'اضافة ميزة', 'مميزات الخدمة',NULL, 'services.feature.create,services.feature.store', NULL, NULL),
(37, 'update_services.feature', 'web', 'تعديل مميزات الخدمة', 'مميزات الخدمة',NULL, 'services.feature.update,services.feature.edit', NULL, NULL),
(38, 'delete_services.feature', 'web', 'حذف مميزات الخدمة', 'مميزات الخدمة',NULL, 'services.feature.destroy', NULL, NULL),
(39, 'projects', 'web', 'مشاهدة المشاريع', 'المشاريع',NULL, 'projects.index', NULL, NULL),
(40, 'add_projects', 'web', 'اضافة مشروع', 'المشاريع',NULL, 'projects.create,projects.store', NULL, NULL),
(41, 'update_projects', 'web', 'تعديل المشاريع', 'المشاريع',NULL, 'projects.update,projects.edit', NULL, NULL),
(42, 'delete_projects', 'web', 'حذف المشاريع', 'المشاريع',NULL, 'projects.destroy', NULL, NULL),
(43, 'activate_projects', 'web', 'تفعيل والغاء تفعيل المشاريع', 'المشاريع',NULL, 'projects_activation', NULL, NULL),
(44, 'jobs', 'web', 'مشاهدة الوظائف', 'الوظائف',NULL, 'jobs.index', NULL, NULL),
(45, 'add_jobs', 'web', 'اضافة وظيفة', 'الوظائف',NULL, 'jobs.create,jobs.store', NULL, NULL),
(46, 'update_jobs', 'web', 'تعديل الوظائف', 'الوظائف',NULL, 'jobs.update,jobs.edit', NULL, NULL),
(47, 'delete_jobs', 'web', 'حذف الوظائف', 'الوظائف',NULL, 'jobs.destroy', NULL, NULL),
(48, 'activate_jobs', 'web', 'تفعيل والغاء تفعيل الوظائف', 'الوظائف',NULL, 'jobs_activation', NULL, NULL),
(49, 'pages', 'web', 'مشاهدة الصفحات', 'الصفحات',NULL, 'pages.index', NULL, NULL),
(50, 'add_pages', 'web', 'اضافة صفحة', 'الصفحات', NULL,'pages.create,pages.store', NULL, NULL),
(51, 'update_pages', 'web', 'تعديل الصفحات', 'الصفحات',NULL, 'pages.update,pages.edit', NULL, NULL),
(52, 'delete_pages', 'web', 'حذف الصفحات', 'الصفحات',NULL, 'pages.destroy', NULL, NULL),
(53, 'activate_pages', 'web', 'تفعيل والغاء تفعيل الصفحات', 'الصفحات',NULL, 'pages_activation', NULL, NULL),
(54, 'customers', 'web', 'مشاهدة العملاء', 'العملاء', NULL,'customers.index', NULL, NULL),
(55, 'add_customers', 'web', 'اضافة عميل', 'العملاء', NULL,'customers.create,customers.store', NULL, NULL),
(56, 'update_customers', 'web', 'تعديل العملاء', 'العملاء',NULL, 'customers.update,customers.edit', NULL, NULL),
(57, 'delete_customers', 'web', 'حذف العملاء', 'العملاء', NULL,'customers.destroy', NULL, NULL),
(58, 'activate_customers', 'web', 'تفعيل والغاء تفعيل العملاء', 'العملاء',NULL, 'customers_activation', NULL, NULL),
(59, 'contacts', 'web', 'مشاهدة الرسائل', 'الرسائل',NULL, 'contacts.index', NULL, NULL),
(60, 'show_contacts', 'web', 'مشاهدة تفاصيل الرسالة', 'الرسائل',NULL, 'contacts.show', NULL, NULL),
(61, 'delete_contacts', 'web', 'حذف الرسائل', 'الرسائل',NULL, 'contacts.destroy', NULL, NULL),
(62, 'roles', 'web', 'مشاهدة الصلاحيات', 'الصلاحيات',NULL, 'roles.index', NULL, NULL),
(63, 'add_roles', 'web', 'اضافة صلاحية', 'الصلاحيات',NULL, 'roles.create,roles.store', NULL, NULL),
(64, 'update_roles', 'web', 'تعديل الصلاحيات', 'الصلاحيات',NULL, 'roles.update,roles.edit', NULL, NULL),
(65, 'delete_roles', 'web', 'حذف الصلاحيات', 'الصلاحيات',NULL, 'roles.destroy', NULL, NULL),
(66, 'users', 'web', 'مشاهدة المستخدمين', 'المستخدمين',NULL, 'users.index', NULL, NULL),
(67, 'add_users', 'web', 'اضافة مستخدم', 'المستخدمين',NULL, 'users.create,users.store', NULL, NULL),
(68, 'update_users', 'web', 'تعديل المستخدمين', 'المستخدمين',NULL, 'users.update,users.edit', NULL, NULL),
(69, 'delete_users', 'web', 'حذف المستخدمين', 'المستخدمين',NULL, 'users.destroy', NULL, NULL),
(70, 'activate_users', 'web', 'تفعيل والغاء تفعيل المستخدمين', 'المستخدمين',NULL, 'users_activation', NULL, NULL),
(71, 'settings', 'web', 'التعديل في اعدادات التطبيق', 'اعدادات التطبيق',NULL, 'settings_get,settings_post', NULL, NULL);
COMMIT;
